### ISSUE TITLE
Noob Question. Best way to restart search after crash..

### ISSUE THREAD

**Issue by JoshCourt** [NikolaiT/se-scraper#26]
Hi all.

If the scraper crashes half way through a search.  How do i reset the scraper to start from the search results page it was last on?

Is this set through "Query String Parameters" ? 
If it is I have tried to add this to the advanced usage script but had no luck,  I keep getting this error when starting the script.

/test.js:26
    verbose: true,
           ^

SyntaxError: Unexpected token :
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by NikolaiT** [comment]
This would need some caching on our side. This is currently not planned.
