### ISSUE TITLE
Browser Disconnect after crash

### ISSUE THREAD

**Issue by naqushab** [NikolaiT/se-scraper#31]
I am using Bing Search to crawl search results but after a while it throws an error and fails to continue after that saying browser is disconnected:
Here is the log:
```
Problem with scraping Marketing-Literatur filetype:pdf in search engine bing: Error: Navigation failed because browser has disconnected!
(node:11024) UnhandledPromiseRejectionWarning: Error: Timeout hit: 120000
    at Object.<anonymous> (C:\Users\neyazee\node_modules\se-scraper\src\puppeteer-cluster\dist\util.js:67:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\neyazee\node_modules\se-scraper\src\puppeteer-cluster\dist\util.js:4:58)
    at <anonymous>
(node:11024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[i] bing scrapes keyword "Sachbuchgeschichte filetype:pdf" on page 7
```

My code to crawl Bing:
```
var fs = require('fs');
var path = require('path');
var os = require("os");

const se_scraper = require('se-scraper');

var filepath_de = path.join(__dirname, '/data/keywords_de.txt');
var filepath_fr = path.join(__dirname, '/data/keywords_fr.txt');

function read_keywords_from_file(fpath) {
    let kws =  fs.readFileSync(fpath).toString().split(os.EOL);
    // clean keywords
    kws = kws.filter((kw) => {
        return kw.trim().length > 0;
    });
    return kws;
}

let keywords_fr = read_keywords_from_file(filepath_fr);
let keywords_de = read_keywords_from_file(filepath_de);

const Cluster = {
    CONCURRENCY_PAGE: 1, // shares cookies, etc.
    CONCURRENCY_CONTEXT: 2, // no cookie sharing (uses contexts)
    CONCURRENCY_BROWSER: 3, // no cookie sharing and individual processes (uses contexts)
};


// those options need to be provided on startup
// and cannot give to se-scraper on scrape() calls
let browser_config = {
    // the user agent to scrape with
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36',
    // if random_user_agent is set to True, a random user agent is chosen
    random_user_agent: true,
    verbose: true,
    // whether to start the browser in headless mode
    headless: false,
    // whether debug information should be printed
    // level 0: print nothing
    // level 1: print most important info
    // ...
    // level 4: print all shit nobody wants to know
    debug_level: 2,
    is_local: false,
    throw_on_detection: false,
    puppeteer_cluster_config: {
        headless: false,
        timeout: 2 * 60 * 1000, // max timeout set to 2 minutes
        monitor: false,
        concurrency: 3, // one scraper per tab
        maxConcurrency: 5, // scrape with 5 tabs
    }
};

(async () => {
    // scrape config can change on each scrape() call

    // scrape config can change on each scrape() call
    let scrape_config_bing_de = {
        // which search engine to scrape
        search_engine: 'bing',
        // an array of keywords to scrape
        keywords: keywords_de,
        // the number of pages to scrape for each keyword
        num_pages: 10,

        // OPTIONAL PARAMS BELOW:
        // https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-web-api-v5-reference#query-parameters
        bing_settings: {
            cc: 'DE', // The cc parameter determines the country to use for the query.
            mkt: 'de-DE', // The mkt parameter determines the UI language to return results.
            offset: 0, // Determines the results offset to use, defaults to 0.
            count: 20, // Determines the number of results to show, defaults to 10. Maximum is 100.
        },
        // how long to sleep between requests. a random sleep interval within the range [a,b]
        // is drawn before every request. empty string for no sleeping.
        sleep_range: '',
        // path to output file, data will be stored in JSON
        output_file: 'results/bing_de.json',
        // whether to prevent images, css, fonts from being loaded
        // will speed up scraping a great deal
        block_assets: true,
        // check if headless chrome escapes common detection techniques
        // this is a quick test and should be used for debugging
        test_evasion: false,
        apply_evasion_techniques: true,
        // log ip address data
        log_ip_address: false,
        // log http headers
        log_http_headers: false,
    };

    let results = await se_scraper.scrape(browser_config, scrape_config_bing_de);
    console.dir(results, {depth: null, colors: true});

})();
```

Is there something I am missing here?

**Comment by NikolaiT** [comment]
I can't say for sure what causes it, I tried your script and it looks good.

I added the functionality to make a screenshot upon failure, this will at least give us a hint if for example bing blocked the scraping. 

Right now I can't detect whether bing is blocking the scraping because bing never blocked me.

Did that happen to you?

**Comment by naqushab** [comment]
Nope. Bing wasn't blocking me as opposed to Google which was blocking constantly. This is the problem with the puppeteer itself, I guess. On encountering this error, It just closes all the browsers and tabs and only one empty tab opens up.

**Comment by NikolaiT** [comment]
The error seems to originate from puppeteer-cluster:

```js
exports.formatDuration = formatDuration;
function timeoutExecute(millis, promise) {
    return __awaiter(this, void 0, void 0, function* () {
        let timeout = null;
        const result = yield Promise.race([
            (() => __awaiter(this, void 0, void 0, function* () {
                yield new Promise((resolve) => {
                    timeout = setTimeout(resolve, millis);
                });
                throw new Error(`Timeout hit: ${millis}`);
            }))(),
            (() => __awaiter(this, void 0, void 0, function* () {
                try {
                    return yield promise;
                }
                catch (error) {
                    // Cancel timeout in error case
                    clearTimeout(timeout);
                    throw error;
                }
            }))(),
        ]);
        clearTimeout(timeout); // is there a better way?
        return result;
    });
}
```

But I don't know either what causes it.

**Comment by naqushab** [comment]
Is there any workaround to this?

**Comment by NikolaiT** [comment]
Maybe try another puppeteer version? In the past I had some problems with broken puppeteer versions...

**Comment by NikolaiT** [comment]
Oh my good I am too stupid, this is the 2 minute timeout that gets triggered that you can set in the config:

```json

    puppeteer_cluster_config: {
        headless: false,
        timeout: 2 * 60 * 1000, // max timeout set to 2 minutes
        monitor: false,
        concurrency: 3, // one scraper per tab
        maxConcurrency: 5, // scrape with 5 tabs
    }

```

Set this to 5 hours:

```json
    puppeteer_cluster_config: {
        headless: false,
        timeout: 5 * 60 * 60 * 1000, // max timeout set to 2 minutes
        monitor: false,
        concurrency: 3, // one scraper per tab
        maxConcurrency: 5, // scrape with 5 tabs
    }
```

**Comment by naqushab** [comment]
Ohhh.. I thought it was a per keyword, per scrape job timeout.. Thanks @NikolaiT :)
