### ISSUE TITLE
The browser does not start in docker

### ISSUE THREAD

**Issue by lingharto** [NikolaiT/se-scraper#49]
I follow the instructions completely, however, I get an error
```
Running on http://0.0.0.0:3000
[i] [se-scraper] started at [Sun, 15 Sep 2019 20:47:56 GMT] and scrapes google with 1 keywords on 1 pages each.
[i] Using startUrl: https://www.google.com
(node:1) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
    at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onClosed (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/lib/Connection.js:215:10)
    at Connection._onClose (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/lib/Connection.js:138:15)
    at WebSocketTransport._ws.addEventListener.event (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/lib/WebSocketTransport.js:48:22)
    at WebSocket.onClose (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.emitClose (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/node_modules/ws/lib/websocket.js:850:15)
    at Socket.emit (events.js:198:13)
  -- ASYNC --
    at Frame.<anonymous> (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/se-scraper/src/puppeteer-cluster/node_modules/puppeteer/lib/helper.js:112:23)
    at GoogleScraper.load_start_page (/se-scraper/src/modules/google.js:177:46)
    at GoogleScraper.load_search_engine (/se-scraper/src/modules/se_scraper.js:137:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by NikolaiT** [comment]
Might be a puppeteer issue. Please try again with the updated docker image. Instructions here: https://github.com/NikolaiT/se-scraper#docker-support
